### PR TITLE
Make fitting of the GOK more robust in calc_Huntley2006()

### LINKED ISSUE #660: make calc_Huntley2006() fitting more robust
This example shows a case of failure of the fit with the GOK model, while the EXP model can be fitted:
```R
DRC <- data.frame(
   Dose = c(rep(0, 7), rep(500, 12), rep(1000, 6), rep(2000, 6)),
   Lx.Tx = c(1.79, rep(0.06, 6), rep(0.97, 12), rep(1.80, 6), rep(3.20, 6)),
   Lx.Tx.Err = c(0.038, rep(0.001, 6), rep(0.021, 12), rep(0.038, 6), rep(0.068, 6))
)
calc_Huntley2006(
  data = DRC,
  rhop = c(7.67e-7, 2.84e-7),
  fit.method = "GOK",
  readerDdot = c(0.0868, 0.005),
  ddot = c(2.372, 0.199)
)

# Error: [calc_Huntley2006()] Could not fit simulated curve, check suitability of model and parameters
```

Our aim is to make the fitting more robust, so that these failure should happen more rarely.

### PR DESCRIPTION
**Pull request by mcol**
When fitting the simulated curve with the `GOK` model fails, the fit is attempted again with 100 different values for `D0` and the best fit is used. This should reduce the number of occasions in which the error message "Could not fit simulated
model curve, check suitability of model and parameters" is reported.

When I made the simulated curve of the testcase work, I started getting an error in the fitting of the unfaded curve (the fit failed with "Missing value or an infinity produced when evaluating the model" from `nlsLM`). I reckon that what happens is that we take the starting values from the exponential model, and in that case the `c` parameter was negative, so at first I took its absolute value, but then I settled on the following change, which fixed that error and got a solution for the testcase:

```diff
-   c = coef(fit_start)[["c"]],
+   c = max(coef(fit_start)[["c"]], 1),
```

Fixes #660.

### CODE REVIEW

**Comment by RLumSK** [comment]
Thanks @mcol. Could you make als dataset I had sent work?

**Comment by mcol** [comment]
The testcase I've added is derived from the first dataset you sent me, just with values rounded to 2 decimal places. Your original dataset works too, just very slowly (~30 minutes) as it asks for 10000 MC iterations, and each of them now has to fit 100 models for the simulated curve. I got results testing with `n.MC = 100` in ~20 seconds.

File: R/calc_Huntley2006.R [hunk 1]
```diff
@@ -540,17 +546,48 @@ calc_Huntley2006 <- function(
...
+                  start = start[-2],
+                  lower = lower.bounds[-2],
+                  upper = upper.bounds[-2],
+                  control = list(maxiter = settings$maxiter)),
+                 silent = TRUE)
+
+        if (inherits(t, "try-error"))
+          return(NULL)
+        return(t)
+      })
```
Comment (RLumSK) [inline R/calc_Huntley2006.R:569]: I think we should I think we should parallelise this part to let it run faster on multicore machines.

**Review by RLumSK — CHANGES_REQUESTED** [review]
Upon thorough examination, particularly regarding the extended execution times, it becomes evident that we should consider dividing the computation into distinct processes to harness the capabilities of multicore systems.

**Comment by mcol** [comment]
This takes the time to run 10,000 MC iterations on your example with 10 cores to ~5 minutes.

**Review by RLumSK — COMMENTED** [review]
Great @mcol!
