### PR TITLE
Fix cex setting in the summary/legend text of plot_DRTResults()

### LINKED ISSUE #765: incorrect scaling of legend in plot_DRTPlot()
This happens at `cex = 2`:

Image

Similar to #746.

### PR DESCRIPTION
**Pull request by mcol**
Fixes #765.

### CODE REVIEW

File: R/plot_DRTResults.R [hunk 1]
```diff
@@ -488,7 +491,7 @@ plot_DRTResults <- function(
                y = summary.pos[2],
                adj = summary.adj,
                labels = label.text[[i]],
-               cex = 0.8 * cex,
+               cex = 0.8,
```
Comment (RLumSK) [inline R/plot_DRTResults.R:494]: I have to admit that this was in a scaler on purpose. However, if it works without `* cex`. Fine with me.

**Review by RLumSK — COMMENTED** [review]
There is only one comment, and it is for you to decide.

File: R/plot_DRTResults.R (hunk 1 above)
Comment (mcol) [reply R/plot_DRTResults.R:494]: There's an annoying difference between how the `cex` option is interpreted inside `text()` and `legend()`, which is different from how it's interpreted in `mtext()` and other plotting functions. In those two functions the docs say:  

> cex: character expansion factor *relative* to current  ‘par("cex")’.

Comment (RLumSK) [reply R/plot_DRTResults.R:494]: OK, perhaps this has also changed or I never understood how it is implemented. Thanks either way.
